version: "3.6"
services:

##PROXY TRAEFIK
  reverse-proxy:
    image: traefik:v2.5.4
    restart: always
    command: 
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --certificatesresolvers.le.acme.email=eng.lucasamaral@email.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.httpchallenge=false
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    ports:
      - "80:80"    
      - "25000:8080"
      - "8081:8081" 
      - "443:443" 
    container_name: "traefik"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`tccpmbd.tech`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`)) "
      - "traefik.http.routers.dashboard.service=api@internal"
      # Autenticação no dashboard
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=tcc:$$apr1$$KwEWSXOH$$0c61HXSv1FRWl6McTlRtk0"
      #Forme de gerar senha: echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      # acesso https
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

########### BANCO DE DADOS      
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=softplan
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=10000
    command: --max-connections=10000 --connect-timeout=10  --query-cache-limit=4M --query-cache-size=64M --expire-logs-days=10  --bulk-insert-buffer-size=16M --tmp-table-size=256M
                 --max-heap-table-size=2048M
    labels:
      - "traefik.backend=database"
      - "traefik.port=3306"
    ports:
      - 3306:3306

  ############### JAVA API
  pmbd-api:
    build: ./java-api
    image: pmbd-api:1.0.0
    environment:
      app_name: pmbd
      TZ: America/Sao_Paulo
    restart: on-failure
    depends_on: 
      - database
    links:
      - database
    entrypoint: ./wait-for-it.sh database:3306 -s -t 5 -- java -jar /app/payara-micro-5.2020.2.jar --addJars mariadb-java-client-2.4.1.jar --deploy /app/app.war:pmbd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pmbd-api.rule=Host(`tccpmbd.tech`) && PathPrefix(`/pmbd`)"
      - "traefik.http.services.pmbd-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.pmbd-api.entrypoints=websecure"
      - "traefik.http.routers.pmbd-api.tls=true"

############## CI/CD JENKINS
  jenkins:
    image: lsamaral/jenkins:1.0.1
    ports:
      - "8085:8080"
    volumes:
      - ./data/Jenkins/data:/jenkins-data
      - ./data/Jenkins/backup:/srv/backup
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:$HOME/.docker/config.json
    environment:
      - JENKINS_UI_URL=https://tccpmbd.tech/jenkins
      - JENKINS_OPTS= "--prefix=/jenkins"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`tccpmbd.tech`) && PathPrefix(`/jenkins`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=le"


  ############# APLICACAO WEB    
  web:
    build: ./web
    image: portal-pmbd-web:1.0.0   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`tccpmbd.tech`) && PathPrefix(`/portal`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=le"
      - "traefik.http.routers.web.tls=true" 